name: Deploy Laravel to Hpanel

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Hpanel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            git clone https://github.com/ahmakbardev/portfolio_test.git
            chmod +x ~/bin/composer
            echo "export PATH=$HOME/bin:$PATH" >> ~/.bash_profile
            source ~/.bash_profile
            which composer
            composer --version
            cd ${{ secrets.SERVER_PATH }}/portfolio_test/
            cp .env.example .env
            git pull origin develop
            composer install
            php artisan key:generate
            ln -s ${{ secrets .SERVER_PATH }}/portfolio_test/public ${{ secrets.SERVER_PATH }}/public_html/staging

        # git config --global user.email "ahmakbar.dev@gmail.com"
        # git config --global user.name "ahmakbardev"