name: First Update Staging Laravel to Hpanel

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: First Update Staging to Hpanel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            chmod +x ~/bin/composer
            echo "export PATH=$HOME/bin:$PATH" >> ~/.bash_profile
            source ~/.bash_profile
            which composer
            composer --version
            cd ${{ secrets.SERVER_PATH }}/portfolio_test/
            git config --global  pull.ff true
            git stash
            git pull origin develop
            composer update
            php artisan queue:restart
            php artisan cache:clear
            php artisan route:clear
            php artisan config:clear
            php artisan view:clear
